### PR TITLE
feat(ui): add custom js editor in create test screen (#465)

### LINKED ISSUE #465: UI: Add custom JS editor in create test screen
**Is your feature request related to a problem? Please describe.**
In order to run custom JS in a test, there are too many steps:
1. First needed to create a processor in the UI/API and insert there the custom JS
2. Select this processor in the create test menu
3. For each scenario/step, choose the correct function that's defined in the processor.

Since the custom JS is directly related to the step/scenario written - this flow should be initiated directly from the create test screen.

**Describe the solution you'd like**
Add another tab to the step/scenario screen when creating a test that will open up a similar JS file editor that is currently implemented in the `processors` part of the UI. 

1. If the tab is for a scenario, have the following function signatures in the JS editor:
```
function beforeScenario(context, ee, next) {
    return next(); // MUST be called for the scenario to continue
}
function afterScenario(context, ee, next) {
    return next(); // MUST be called for the scenario to continue
}

```

2. if the tab is for a step, have the following function signatures in the JS editor:
```
function beforeRequest(requestParams, context, ee, next) {
    return next(); // MUST be called for the scenario to continue
}
function afterResponse(requestParams, response, context, ee, next) {
    return next(); // MUST be called for the scenario to continue
}
```

**Additional context**
Current create test screen:
image

The `JS` icon should be to the left of the duplicate icon
Icon to use: 
image 
 https://fontawesome.com/icons/node-js?style=brands with smallest size
With Predator's color scheme: `#0d47ff`

### PR DESCRIPTION
**Pull request by alexandravassova**
new tab in step/scenario screen that opens JS editor, currently without backend functionality
Closes #465

### CODE REVIEW

**Comment by NivLipetz** [comment]
@alexandravassova thanks alot for the PR! it's greatly appreciated! The icon inside the create test form looks great 😄 
The only thing I'm a little skeptic about is when clicking on the custom JS button a new window opens up and it seems a little out of place. I have the following suggestion tell me what you think:

1. I realize this wasn't mentioned in the issue but I think it would be best if we can have the custom JS inside the create test form underneath the `body` and above the `expectations`.
Essentially here:
image

2. In the scenario tab I suggest to place it here:
image

3. Since we will have it inside the actual test form, we don't need the `cancel` and `submit` buttons that the original new window would open up with.

4. Last small thing, the scenario tabs don't have a `|` divider in between the icons (js editor and duplicate) whereas in the step tabs there is a `|` divider, can you please add the divider also to the scenarios tab to make it even with the rest of the form?
image

Again thanks a lot! I'm open for any questions/comments you have

**Comment by alexandravassova** [comment]
ok, i am going to implement your suggestions, they make sense :)

**Comment by NivLipetz** [comment]
@alexandravassova it looks great and exactly how I pictured it 😄  really nice job!
@manorlh will add his review this hopefully tonight or tomorrow at latest. Thanks a lot for the contribution!

**Comment by enudler** [comment]
hi, @alexandravassova great work!
I'm going merge it to a feature branch as we need to implement the backend
I think it will count for hacktoberfest but it doesn't just let me know.

We will open an issue today for backend implementation, if you would like to participate LMK
Thanks again for the great PR!

**Pull request merged**
