### PR TITLE
fix(openapi): fixed missing schema key

### PR DESCRIPTION
**Pull request by syncush**
| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |

Further  information:
A schema key was missing

### CODE REVIEW

**Review by enudler — CHANGES_REQUESTED** [review]
hi 
can you please update:

docs/devguide/docs/swagger-docs.yaml

this is the spec that is published as redoc in our docs

**Comment by syncush** [comment]
@enudler then if we have 2 docs we must have 1

**Comment by enudler** [comment]
@syncush i wish.. put the problem that our swagger validator and the redoc needs slight changes from each other :|

**Comment by syncush** [comment]
Can you please provide an example, there must be a way

**Comment by enudler** [comment]
it was quite a long ago when we decided on it
but as far as I remember redoc didn't support discriminators

to test this you can do:

`cd docs/devguide
mkdocs serve
`
and go to 

http://localhost:8000/indexapiref.html#operation/create-a-test

you will see that it doesn't list the request body very well..

**Comment by enudler** [comment]
btw it can be also the opposite, that redoc does it well and we used slightly changed swagger to support validators

**Comment by syncush** [comment]
@enudler I added a validator test for the `openapi3` spec

**Pull request merged**
