### PR TITLE
fix-uiSwitcher-value

### PR DESCRIPTION
**Pull request by ShubhamSood1406**
| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                      |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |

Related issues: #421

Further  information:
- I set the default values of the switcher to true

### CODE REVIEW

**Comment by enudler** [comment]
@ShubhamSood1406 you needed to change only the gzip default value to true
you changed component default

**Comment by ShubhamSood1406** [comment]
@enudler I take that in wrong way. I now corrected it.

**Comment by enudler** [comment]
Hi @ShubhamSood1406 
Unfortunately not

If you want you can play with the project, run it, and take some other issue.

**Comment by ShubhamSood1406** [comment]
@enudler Can you please remove the invalid label from this PR or delete this PR, otherwise it will affect my participation in Hacktoberfest.

**Pull request closed without merging**
